# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('num', models.IntegerField()),
                ('buk', models.CharField(max_length=5)),
                ('prim', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'doma',
                'ordering': ['num', 'buk'],
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prim', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'streets',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dom',
            name='dom_street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Street'),
        ),
    ]
