# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
    ]
