# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 01:34
from __future__ import unicode_literals

from django.db import migrations, models


def load_data(apps, _):
    print('10+++-----10')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mymanager'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
