# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-27 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_kw_mymanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyManager',
        ),
    ]
